server:
  port: 8088

logging:
  level:
    org.springframework: INFO


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  messages:
      basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: passw0rd
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa

management:
  endpoints:
    web:
      exposure:
        include: "*"